This repo contains the dotfiles I share between different Linux & Windows
environments.

* Installation

I use [[https://yadm.io/][yadm]], "yet another dotfiles manager", to manage my dotfiles so first you
need to install yadm. The yadm documentation describes several ways to install
it but if you're in a rush, clone the repo:
#+begin_src sh
git clone https://github.com/TheLocehiliosan/yadm.git
#+end_src
You can find the ~yadm~ script in the root of the workspace.

To install the dotfiles in this repo, execute
#+begin_src sh
yadm/yadm clone https://github.com/swinkels/yadm-dotfiles.git
#+end_src
Note the following comment from the yadm documentation:
#+begin_quote
If a file already exists locally and has content that differs from
the one in the repository, the local file will be left unmodified and you’ll
have to review and resolve the differences.
#+end_quote

* How does yadm work?

In effect, yadm uses a bare Git repo in ~~/.local/share/yadm/repo.git~ with your
home directory as a work tree. This repo doesn't show untracked files, so a
~yadm status~ only checks files that are managed by Git.

yadm uses a different approach to support the [[https://yadm.io/docs/alternates][alternate files]], which are
variants of the same file. It depends on your "environment" which variant yadm
will install, for example on the OS used or on the name of the machine name. You
create every variant in a special directory, namely ~/.config/yadm/alt~. Then,
when you execute ~yadm clone~ or ~yadm pull~, yadm creates a link to the correct
variant in the root of your home directory.

On Windows, or rather, on NTFS, yadm doesn't use symbolic links and creates a
well-named copy of the variant instead. This means that if you need to modify
such a file, you have to edit the original file in ~/.config/yadm/alt~ and
reinstall the alternate files. You don't have this limitation on Linux, where
most file systems support symbolic links.
